"""empty message

Revision ID: 1dca4dc6689d
Revises: None
Create Date: 2015-09-15 14:54:16.117897

"""

# revision identifiers, used by Alembic.
revision = '1dca4dc6689d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
