"""empty message

Revision ID: 3ed70310099d
Revises: 1dca4dc6689d
Create Date: 2015-09-30 23:20:59.632852

"""

# revision identifiers, used by Alembic.
revision = '3ed70310099d'
down_revision = '1dca4dc6689d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'description')
    ### end Alembic commands ###
